// ===== DO NOT EDIT, CHANGES WILL BE OVERWRITTEN =====
// automatically generated by get_contributor_user_info.py

package com.ghhccghk.musicplay.data

import android.net.Uri
import com.ghhccghk.musicplay.R

object Contributors {
    private fun decode(text: String?) = text?.let { Uri.decode(it) }
    val LIST = listOf(
        GitHubUser(login = "ghhccghk", name = decode("%E6%9D%8E%E5%A4%AA%E7%99%BD"), avatar = R.drawable.contributor_ghhccghk, contributed = R.string.contributors_ghhccghk),
    )
}
